# Generated by Django 2.2.10 on 2021-12-15 17:01

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Once\\Documents\\eoj3\\repo'), upload_to='assets/%Y%m%d/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='case',
            name='input_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Once\\Documents\\eoj3\\repo'), upload_to='cases/%Y%m%d/', verbose_name='输入文件'),
        ),
        migrations.AlterField(
            model_name='case',
            name='output_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Once\\Documents\\eoj3\\repo'), upload_to='cases/%Y%m%d/', verbose_name='输出文件'),
        ),
    ]
