# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-18 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0002_auto_20180218_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='points',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
