# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-18 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0003_case_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='alias',
        ),
    ]
