# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-27 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0004_remove_revision_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='in_tests',
        ),
    ]
