# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-02 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0013_taginfo'),
        ('polygon', '0005_remove_case_in_tests'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='revision',
            unique_together=set([('problem', 'revision')]),
        ),
    ]
