# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-02 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0006_auto_20180302_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.TextField(blank=True, max_length=256)),
                ('status', models.IntegerField(choices=[(-3, 'PENDING'), (-2, 'RUNNING'), (-1, 'FAILED'), (0, 'OK'), (1, 'ABORTED')], default=-3)),
                ('report', models.TextField(blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polygon.Revision')),
            ],
        ),
    ]
