# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-02 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0008_auto_20180430_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='group_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revision',
            name='group_points',
            field=models.TextField(blank=True),
        ),
    ]
