# Generated by Django 2.1.3 on 2019-01-12 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0014_auto_20190112_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeforcespackage',
            name='create_time',
        ),
        migrations.AddField(
            model_name='package',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
