# Generated by Django 2.1.7 on 2019-03-02 23:28

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0016_codeforcespackage_size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='editsession',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='editsession',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='editsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='run',
            name='user',
        ),
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/ultmaster/Projects/eoj3/repo'), upload_to='assets/%Y%m%d/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='case',
            name='input_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/ultmaster/Projects/eoj3/repo'), upload_to='cases/%Y%m%d/', verbose_name='输入文件'),
        ),
        migrations.AlterField(
            model_name='case',
            name='output_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/ultmaster/Projects/eoj3/repo'), upload_to='cases/%Y%m%d/', verbose_name='输出文件'),
        ),
        migrations.AlterField(
            model_name='codeforcespackage',
            name='status',
            field=models.IntegerField(choices=[(-1, '下载中'), (-2, '运行中'), (0, '成功'), (1, '失败')], default=-1),
        ),
        migrations.DeleteModel(
            name='EditSession',
        ),
        migrations.DeleteModel(
            name='Run',
        ),
    ]
