# Generated by Django 2.2.3 on 2019-07-14 19:46

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygon', '0020_auto_20190711_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='D:\\Coding\\eoj3\\repo'), upload_to='assets/%Y%m%d/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='case',
            name='input_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='D:\\Coding\\eoj3\\repo'), upload_to='cases/%Y%m%d/', verbose_name='输入文件'),
        ),
        migrations.AlterField(
            model_name='case',
            name='output_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='D:\\Coding\\eoj3\\repo'), upload_to='cases/%Y%m%d/', verbose_name='输出文件'),
        ),
    ]
