# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-23 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170406_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='privilege',
            field=models.CharField(choices=[('user', 'Regular User'), ('admin', 'Admin'), ('root', 'Root'), ('volunteer', 'Volunteer')], default='user', max_length=12),
        ),
    ]
