# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-27 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20170825_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-score']},
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
