# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-14 19:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20170908_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('change_username', 'Change Username'), ('download_case', 'Download Case'), ('reward', 'Reward'), ('transfer', 'Transfer')], max_length=20)),
                ('detail_message', models.TextField(blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('credit', models.FloatField()),
                ('balance', models.FloatField()),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='username_change_attempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
