# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-07 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20170928_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_subscription',
            field=models.BooleanField(default=True),
        ),
    ]
