# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-13 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20180107_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='privilege',
        ),
    ]
