# Generated by Django 2.1.3 on 2018-11-06 12:12

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20180713_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('change_username', '更改用户名'), ('download_case', '下载数据'), ('reward', '奖励'), ('transfer', '转账')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar/default.jpg', upload_to='avatar', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': '该电子邮箱已被使用。'}, max_length=192, unique=True, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='magic',
            field=models.CharField(blank=True, choices=[('red', '红'), ('green', '绿'), ('teal', '青'), ('blue', '蓝'), ('purple', '紫'), ('orange', '橙'), ('grey', '灰')], max_length=18, verbose_name='魔法'),
        ),
        migrations.AlterField(
            model_name='user',
            name='motto',
            field=models.CharField(blank=True, max_length=192, verbose_name='励志铭'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_lang',
            field=models.CharField(choices=[('c', 'C'), ('cpp', 'C++11'), ('python', 'Python 3'), ('java', 'Java 8'), ('cc14', 'C++14'), ('cc17', 'C++17'), ('cs', 'C#'), ('py2', 'Python 2'), ('scipy', 'Python (SCI)'), ('php', 'PHP 7'), ('perl', 'Perl'), ('hs', 'Haskell'), ('js', 'Javascript'), ('ocaml', 'OCaml'), ('pypy', 'PyPy'), ('pypy3', 'PyPy 3'), ('pas', 'Pascal'), ('rs', 'Rust'), ('scala', 'Scala'), ('text', 'Text')], default='cpp', max_length=12, verbose_name='语言偏好'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, max_length=64, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='user',
            name='show_tags',
            field=models.BooleanField(default=True, verbose_name='展示标签'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': '该用户名已经存在。'}, max_length=30, unique=True, validators=[account.models.UsernameValidator(), account.models.UsernameLengthValidator(6)], verbose_name='用户名'),
        ),
    ]
