# Generated by Django 2.1.3 on 2018-11-13 19:07

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20181109_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('change_username', 'Change Username'), ('download_case', 'Download Case'), ('reward', 'Reward'), ('transfer', 'Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar/default.jpg', upload_to='avatar', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email has already been used.'}, max_length=192, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_subscription',
            field=models.BooleanField(default=True, verbose_name='Email subscription'),
        ),
        migrations.AlterField(
            model_name='user',
            name='magic',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('green', 'Green'), ('teal', 'Teal'), ('blue', 'Blue'), ('purple', 'Purple'), ('orange', 'Orange'), ('grey', 'Grey')], max_length=18, verbose_name='magic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='motto',
            field=models.CharField(blank=True, max_length=192, verbose_name='motto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_lang',
            field=models.CharField(choices=[('c', 'C'), ('cpp', 'C++11'), ('python', 'Python 3'), ('java', 'Java 8'), ('cc14', 'C++14'), ('cc17', 'C++17'), ('cs', 'C#'), ('py2', 'Python 2'), ('scipy', 'Python (SCI)'), ('php', 'PHP 7'), ('perl', 'Perl'), ('hs', 'Haskell'), ('js', 'Javascript'), ('ocaml', 'OCaml'), ('pypy', 'PyPy'), ('pypy3', 'PyPy 3'), ('pas', 'Pascal'), ('rs', 'Rust'), ('scala', 'Scala'), ('text', 'Text')], default='cpp', max_length=12, verbose_name='preferred language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, max_length=64, verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='user',
            name='show_tags',
            field=models.BooleanField(default=True, verbose_name='show tags'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='student id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=30, unique=True, validators=[account.models.UsernameValidator(), account.models.UsernameLengthValidator(6)], verbose_name='username'),
        ),
    ]
