# Generated by Django 2.1.7 on 2019-03-15 11:34

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20181113_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar/default.jpg', upload_to='avatar', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email has already been used.'}, max_length=192, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_subscription',
            field=models.BooleanField(default=True, verbose_name='邮件订阅'),
        ),
        migrations.AlterField(
            model_name='user',
            name='magic',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('green', 'Green'), ('teal', 'Teal'), ('blue', 'Blue'), ('purple', 'Purple'), ('orange', 'Orange'), ('grey', 'Grey')], max_length=18, verbose_name='魔法'),
        ),
        migrations.AlterField(
            model_name='user',
            name='motto',
            field=models.CharField(blank=True, max_length=192, verbose_name='警句'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_lang',
            field=models.CharField(choices=[('c', 'C'), ('cpp', 'C++11'), ('cc14', 'C++14'), ('cc17', 'C++17'), ('py2', 'Python 2'), ('python', 'Python 3'), ('pypy', 'PyPy'), ('pypy3', 'PyPy 3'), ('java', 'Java 8'), ('pas', 'Pascal'), ('scala', 'Scala'), ('text', 'Text')], default='cpp', max_length=12, verbose_name='偏好语言'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, max_length=64, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='user',
            name='show_tags',
            field=models.BooleanField(default=True, verbose_name='显示标签'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=30, unique=True, validators=[account.models.UsernameValidator(), account.models.UsernameLengthValidator(6)], verbose_name='用户名'),
        ),
    ]
