# Generated by Django 2.2.9 on 2020-02-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OldDiscussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=192)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('problem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OldSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('c', 'C'), ('cpp', 'C++11'), ('cc14', 'C++14'), ('cc17', 'C++17'), ('py2', 'Python 2'), ('python', 'Python 3'), ('pypy', 'PyPy'), ('pypy3', 'PyPy 3'), ('java', 'Java 8'), ('pas', 'Pascal'), ('text', 'Text')], default='cpp', max_length=12)),
                ('code', models.TextField(blank=True)),
                ('problem', models.IntegerField()),
                ('author', models.CharField(max_length=192)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('judge_start_time', models.DateTimeField(blank=True, null=True)),
                ('judge_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(-4, 'Submitted'), (-3, 'In queue'), (-2, 'Running'), (-1, 'Wrong answer'), (0, 'Accepted'), (1, 'Time limit exceeded'), (2, 'Idleness limit exceeded'), (3, 'Memory limit exceeded'), (4, 'Runtime error'), (5, 'Denial of judgement'), (6, 'Compilation error'), (7, 'Partial score'), (10, 'Rejected'), (11, 'Checker error'), (12, 'Pretest passed')], default=-3)),
                ('status_percent', models.IntegerField(default=0)),
                ('status_detail', models.TextField(blank=True)),
                ('status_time', models.IntegerField(default=0)),
                ('status_memory', models.IntegerField(default=0)),
                ('code_length', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='OldUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=192)),
                ('password', models.CharField(max_length=192)),
                ('school', models.CharField(max_length=192)),
                ('email', models.CharField(max_length=192)),
            ],
        ),
    ]
