# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldsubmission',
            name='lang',
            field=models.CharField(choices=[('c', 'C'), ('cpp', 'C++'), ('python', 'Python 3'), ('java', 'Java 8')], default='cpp', max_length=12),
        ),
    ]
