# Generated by Django 2.2.9 on 2020-02-04 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0001_initial'),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('c', 'C'), ('cpp', 'C++11'), ('cc14', 'C++14'), ('cc17', 'C++17'), ('py2', 'Python 2'), ('python', 'Python 3'), ('pypy', 'PyPy'), ('pypy3', 'PyPy 3'), ('java', 'Java 8'), ('pas', 'Pascal'), ('text', 'Text')], default='cpp', max_length=12, null=True)),
                ('code', models.TextField(blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('judge_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(-4, 'Submitted'), (-3, 'In queue'), (-2, 'Running'), (-1, 'Wrong answer'), (0, 'Accepted'), (1, 'Time limit exceeded'), (2, 'Idleness limit exceeded'), (3, 'Memory limit exceeded'), (4, 'Runtime error'), (5, 'Denial of judgement'), (6, 'Compilation error'), (7, 'Partial score'), (10, 'Rejected'), (11, 'Checker error'), (12, 'Pretest passed')], db_index=True, default=-4)),
                ('status_percent', models.FloatField(default=0)),
                ('status_detail', models.TextField(blank=True)),
                ('status_time', models.FloatField(blank=True, null=True)),
                ('status_memory', models.FloatField(blank=True, null=True)),
                ('status_message', models.TextField(blank=True)),
                ('status_test', models.PositiveIntegerField(default=0)),
                ('code_length', models.PositiveIntegerField(blank=True, null=True)),
                ('judge_server', models.IntegerField(default=0)),
                ('contest_time', models.DurationField(blank=True, null=True)),
                ('visible', models.BooleanField(db_index=True, default=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest.Contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='submission.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='PrintManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.PositiveIntegerField(default=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrintCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('generated_pdf', models.TextField(blank=True)),
                ('pages', models.PositiveIntegerField(default=1)),
                ('status', models.IntegerField(choices=[(-1, 'Processing'), (0, 'OK'), (1, 'Failed'), (2, 'Ignore')], default=-1)),
                ('comment', models.CharField(blank=True, max_length=64)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.PrintManager')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
