# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-10 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20170508_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='addon_info',
            field=models.BooleanField(default=False),
        ),
    ]
