# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-31 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_auto_20170825_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='rewarded',
            field=models.BooleanField(default=False),
        ),
    ]
