# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-03 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_submission_rewarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status_percent',
            field=models.FloatField(default=0),
        ),
    ]
