# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-04 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_auto_20170903_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='code_length',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
