# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-30 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0008_submission_code_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-create_time']},
        ),
    ]
