# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-01 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0009_auto_20170930_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(-4, 'Submitted'), (-3, 'Waiting'), (-2, 'Judging'), (-1, 'Wrong Answer'), (0, 'Accepted'), (1, 'Time Limit Exceeded'), (2, 'Idleness Limit Exceeded'), (3, 'Memory Limit Exceeded'), (4, 'Runtime Error'), (5, 'System Error'), (6, 'Compile Error'), (7, 'Idleness Limit Exceeded'), (8, 'Time Limit Exceeded'), (11, 'Judge Error'), (12, 'Pretest Passed')], db_index=True, default=-4),
        ),
    ]
