# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-15 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0010_auto_20171001_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
