# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-02 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0012_submission_cheat_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='report_paid',
            field=models.IntegerField(default=0),
        ),
    ]
