# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-05 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0013_submission_report_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='judge_server',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
