# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-05 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0014_submission_judge_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='judge_server',
        ),
    ]
