# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-07 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0016_auto_20180107_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='rewarded',
        ),
        migrations.AddField(
            model_name='submission',
            name='judge_server',
            field=models.IntegerField(default=0),
        ),
    ]
