# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0022_auto_20180822_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='printcode',
            name='comment',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='printcode',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Processing'), (0, 'OK'), (1, 'Failed'), (2, 'Ignore')], default=-1),
        ),
    ]
