# Generated by Django 2.1.3 on 2018-11-06 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0026_remove_submission_status_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest.Contest'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='lang',
            field=models.CharField(choices=[('c', 'C'), ('cpp', 'C++11'), ('python', 'Python 3'), ('java', 'Java 8'), ('cc14', 'C++14'), ('cc17', 'C++17'), ('cs', 'C#'), ('py2', 'Python 2'), ('scipy', 'Python (SCI)'), ('php', 'PHP 7'), ('perl', 'Perl'), ('hs', 'Haskell'), ('js', 'Javascript'), ('ocaml', 'OCaml'), ('pypy', 'PyPy'), ('pypy3', 'PyPy 3'), ('pas', 'Pascal'), ('rs', 'Rust'), ('scala', 'Scala'), ('text', 'Text')], default='cpp', max_length=12),
        ),
    ]
