# Generated by Django 2.1.3 on 2018-11-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0027_auto_20181106_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='contest_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(-4, 'Submitted'), (-3, 'In queue'), (-2, 'Running'), (-1, 'Wrong answer'), (0, 'Accepted'), (1, 'Time limit exceeded'), (2, 'Idleness limit exceeded'), (3, 'Memory limit exceeded'), (4, 'Runtime error'), (5, 'Denial of judgement'), (6, 'Compilation error'), (7, 'Partial score'), (10, 'Rejected'), (11, 'Checker error'), (12, 'Pretest passed')], db_index=True, default=-4),
        ),
    ]
