# Generated by Django 2.1.3 on 2018-11-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0028_auto_20181108_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='code_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='lang',
            field=models.CharField(choices=[('c', 'C'), ('cpp', 'C++11'), ('python', 'Python 3'), ('java', 'Java 8'), ('cc14', 'C++14'), ('cc17', 'C++17'), ('cs', 'C#'), ('py2', 'Python 2'), ('scipy', 'Python (SCI)'), ('php', 'PHP 7'), ('perl', 'Perl'), ('hs', 'Haskell'), ('js', 'Javascript'), ('ocaml', 'OCaml'), ('pypy', 'PyPy'), ('pypy3', 'PyPy 3'), ('pas', 'Pascal'), ('rs', 'Rust'), ('scala', 'Scala'), ('text', 'Text')], default='cpp', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
