# Generated by Django 2.1.7 on 2019-03-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0031_auto_20190315_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='addon_info',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='cheat_tag',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='report_paid',
        ),
        migrations.AddField(
            model_name='submission',
            name='status_memory',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='lang',
            field=models.CharField(choices=[('c', 'C'), ('cpp', 'C++11'), ('cc14', 'C++14'), ('cc17', 'C++17'), ('py2', 'Python 2'), ('python', 'Python 3'), ('pypy', 'PyPy'), ('pypy3', 'PyPy 3'), ('java', 'Java 8'), ('pas', 'Pascal'), ('text', 'Text')], default='cpp', max_length=12, null=True),
        ),
    ]
