# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestproblem',
            name='first_solved_by',
            field=models.IntegerField(default=-1),
        ),
    ]
