# Generated by Django 2.2.10 on 2021-12-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_contestinvitation_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestinvitation',
            name='availability',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
