# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-14 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20170406_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='title',
            field=models.CharField(max_length=192),
        ),
    ]
