# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-23 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_auto_20170414_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestinvitation',
            name='star',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contestparticipant',
            name='star',
            field=models.BooleanField(default=False),
        ),
    ]
