# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-24 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20170423_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipant',
            name='hidden_comment',
            field=models.TextField(blank=True),
        ),
    ]
