# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-29 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0009_contestclarification_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='allowed_lang',
            field=models.CharField(default='c, cpp, java, pas, py2, python', max_length=192, verbose_name='Allowed languages'),
        ),
    ]
