# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-03 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_auto_20170825_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='run_tests_during_contest',
            field=models.CharField(choices=[('all', 'All'), ('pretest', 'Pretests'), ('sample', 'Samples'), ('none', 'None')], default='all', max_length=10),
        ),
    ]
