# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-09 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0013_auto_20170908_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestparticipant',
            options={},
        ),
    ]
