# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-20 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0014_auto_20170909_1132'),
    ]

    operations = [
        migrations.RenameField('Contest', 'manager', 'managers'),
    ]
