# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-29 08:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0018_auto_20171007_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='authors',
            field=models.ManyToManyField(related_name='written_contests', to=settings.AUTH_USER_MODEL),
        ),
    ]
