# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-07 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0019_contest_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='allowed_lang',
            field=models.CharField(default='c,cc14,cpp,cs,hs,java,js,ocaml,pas,perl,php,py2,pypy,python,rs,scala', max_length=192, verbose_name='Allowed languages'),
        ),
    ]
