# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-21 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0021_auto_20180119_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestuserrating',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contestuserrating',
            name='solved',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
