# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-10 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0022_auto_20180121_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='open_problems',
            field=models.BooleanField(default=True, verbose_name='Publish problems after contest'),
        ),
    ]
