# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-13 12:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0024_auto_20180313_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityparticipant',
            name='email',
            field=models.CharField(max_length=192, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
