# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0027_auto_20180318_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityparticipant',
            name='major',
            field=models.CharField(blank=True, choices=[('art', 'Art'), ('accounting', 'Accounting'), ('business', 'Business'), ('business_admin', 'Business Administration'), ('chemistry', 'Chemistry'), ('commerce', 'Commerce'), ('communication', 'Communications'), ('ce', 'Computer Engineering'), ('cs', 'Computer Science'), ('economics', 'Economics'), ('education', 'Education'), ('ee', 'Electrical Engineering'), ('finance', 'Finance'), ('geometry', 'Geometry'), ('interaction', 'Human Computer Interaction'), ('it', 'Information Technology'), ('life', 'Life Science'), ('mechanics', 'Mechanics'), ('linguistics', 'Linguistics'), ('literature', 'Literature'), ('math', 'Mathematics'), ('se', 'Software Engineering'), ('philosophy', 'Philosophy'), ('physics', 'Physics'), ('politics', 'Political Science'), ('psycho', 'Psychology'), ('social', 'Social Science'), ('translation', 'Translation'), ('others', 'Others')], max_length=30),
        ),
    ]
