# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0028_auto_20180326_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='analysis_blog_id',
            field=models.IntegerField(default=0),
        ),
    ]
