# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0031_auto_20180502_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityparticipant',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
