# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 09:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0032_activityparticipant_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='volunteers',
            field=models.ManyToManyField(related_name='volunteering_contests', to=settings.AUTH_USER_MODEL),
        ),
    ]
