# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0037_auto_20180713_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='case_public',
            field=models.PositiveIntegerField(choices=[(0, 'Forbidden'), (1, 'Tests are visible if paid'), (2, 'Tests are always visible')], default=0),
        ),
    ]
