# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0038_auto_20180717_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='penalty_counts',
            field=models.PositiveIntegerField(default=1200, verbose_name='Penalty by seconds'),
        ),
    ]
