# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0039_auto_20180717_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='access_level',
            field=models.PositiveIntegerField(choices=[(0, 'Available only to managers'), (10, 'Available to invited users, problems are always hidden'), (20, 'Available to invited users, problems will be automatically published after contest'), (30, 'Available to everyone, requires registration in advance'), (40, 'Available to everyone')], default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='common_status_access_level',
            field=models.IntegerField(choices=[(-10, 'Close common status and standings'), (0, 'Default (follow access level settings)'), (10, 'Make common status and standings always public')], default=0),
        ),
        migrations.AlterField(
            model_name='contest',
            name='standings_disabled',
            field=models.BooleanField(default=False, verbose_name='Close common status and standings'),
        ),
    ]
