# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0040_auto_20180903_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='open_problems',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='public',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='rated',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='standings_disabled',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='standings_public',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='visible',
        ),
    ]
