# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0041_auto_20180903_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='always_running',
            field=models.BooleanField(default=False, verbose_name='As gym contest (start time and end time will not work)'),
        ),
    ]
