# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0042_auto_20180904_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='always_running',
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_type',
            field=models.IntegerField(choices=[(0, 'Regular Round'), (1, 'Exercise in Gym')], default=0),
        ),
        migrations.AddField(
            model_name='contestparticipant',
            name='join_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='access_level',
            field=models.PositiveIntegerField(choices=[(0, 'Available only to managers'), (10, 'Available to invited users, problems are always hidden'), (15, 'Available to invited users, allow for virtual participation after contest'), (20, 'Available to invited users, problems will be automatically published after contest'), (30, 'Available to everyone, requires registration in advance'), (40, 'Available to everyone')], default=0),
        ),
        migrations.AlterField(
            model_name='contestparticipant',
            name='penalty',
            field=models.BigIntegerField(default=0),
        ),
    ]
