# Generated by Django 2.1.3 on 2018-11-06 12:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0043_auto_20181105_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestparticipant',
            options={'ordering': ('-is_confirmed', '-score', 'penalty', 'star')},
        ),
        migrations.AddField(
            model_name='contestparticipant',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='register_end_time',
            field=models.DateTimeField(blank=True, verbose_name='结束注册时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='register_start_time',
            field=models.DateTimeField(blank=True, verbose_name='开始注册时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=192, unique=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='activityparticipant',
            name='email',
            field=models.CharField(max_length=192, validators=[django.core.validators.EmailValidator()], verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='activityparticipant',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', '男'), ('f', '女'), ('d', '拒绝回答')], max_length=5, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='activityparticipant',
            name='graduate_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='毕业年份'),
        ),
        migrations.AlterField(
            model_name='activityparticipant',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='已确认'),
        ),
        migrations.AlterField(
            model_name='activityparticipant',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
        migrations.AlterField(
            model_name='activityparticipant',
            name='major',
            field=models.CharField(blank=True, choices=[('art', '艺术'), ('accounting', '会计'), ('business', '商业'), ('business_admin', '工商管理'), ('chemistry', '化学'), ('communication', '通信'), ('ce', '计算机工程'), ('cs', '计算机科学'), ('economics', '经济'), ('education', '教育'), ('ee', '电子工程'), ('finance', '金融'), ('geology', '地理'), ('interaction', '人机交互'), ('it', '信息技术'), ('life', '生命科学'), ('mechanics', '机械'), ('linguistics', '语言学'), ('literature', '文学'), ('math', '数学'), ('se', '软件工程'), ('philosophy', '哲学'), ('physics', '物理'), ('politics', '政治学'), ('psycho', '心理学'), ('social', '社会学'), ('translation', '翻译'), ('others', '其他')], max_length=30, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='activityparticipant',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='activityparticipant',
            name='real_name',
            field=models.CharField(max_length=30, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='activityparticipant',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.School', verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='activityparticipant',
            name='student_id',
            field=models.CharField(max_length=30, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='access_level',
            field=models.PositiveIntegerField(choices=[(0, '仅比赛管理员可见'), (10, '仅受邀用户可见，赛后题目不公开'), (15, '仅受邀用户可见，赛后允许虚拟参赛'), (20, '仅受邀用户可见，赛后题目直接公开'), (30, '公开，需要比赛前注册'), (40, '公开')], default=0, verbose_name='访问控制'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='allow_code_share',
            field=models.IntegerField(choices=[(0, '不允许'), (1, '代码在赛后对 AC 用户公开（默认）'), (2, '代码在赛后完全公开'), (3, '代码在比赛过程中对 AC 用户公开')], default=1, verbose_name='允许代码共享'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='allowed_lang',
            field=models.CharField(default='c,cc14,cc17,cpp,cs,hs,java,js,ocaml,pas,perl,php,py2,pypy,pypy3,python,rs,scala,scipy,text', max_length=192, verbose_name='允许语言'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='analysis_blog_id',
            field=models.IntegerField(default=0, verbose_name='题解博客 ID'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='case_public',
            field=models.PositiveIntegerField(choices=[(0, '不允许'), (1, '评测报告有偿公开'), (2, '评测报告总是开放')], default=0),
        ),
        migrations.AlterField(
            model_name='contest',
            name='common_status_access_level',
            field=models.IntegerField(choices=[(-10, '不可见'), (0, '默认'), (10, '总是可见')], default=0, verbose_name='所有提交和榜单的访问控制'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_type',
            field=models.IntegerField(choices=[(0, '常规比赛'), (1, '作业')], default=0),
        ),
        migrations.AlterField(
            model_name='contest',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='freeze',
            field=models.BooleanField(default=False, verbose_name='是否封榜'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='freeze_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='封榜时间'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='ip_sensitive',
            field=models.BooleanField(default=False, verbose_name='首次登录绑定 IP'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='last_counts',
            field=models.BooleanField(default=False, verbose_name='认为最后一次提交有效（默认使用成绩最好的）'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='pdf_statement',
            field=models.FileField(blank=True, null=True, upload_to='contest_statements/%Y%m%d/', verbose_name='PDF 题面'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='penalty_counts',
            field=models.PositiveIntegerField(default=1200, verbose_name='错误提交罚时（秒）'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='run_tests_during_contest',
            field=models.CharField(choices=[('all', '所有测试点'), ('pretest', '只测试 Pretests'), ('sample', '只测试样例'), ('none', '不作测试')], default='all', max_length=10, verbose_name='比赛过程中对代码进行评测'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='scoring_method',
            field=models.CharField(choices=[('acm', 'ACM 赛制'), ('oi', 'OI 赛制'), ('cf', 'School of Data Analysis (SDA) 赛制 (Codeforces...)'), ('tcmtime', 'TCM/TIME 赛制 (GCJ...)')], default='acm', max_length=10, verbose_name='计分规则'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='standings_update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='榜单更新时间'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='standings_without_problem',
            field=models.BooleanField(default=False, verbose_name='排行榜上不显示具体题目的通过情况'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='system_tested',
            field=models.BooleanField(default=False, verbose_name='系统测试准备就绪'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='title',
            field=models.CharField(max_length=192, verbose_name='标题'),
        ),
    ]
