# Generated by Django 2.1.3 on 2018-11-13 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0045_auto_20181108_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestProblemPlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(-1, 'Pending'), (0, 'Ready')])),
                ('identifier', models.CharField(blank=True, max_length=20)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
            ],
        ),
    ]
