# Generated by Django 2.1.7 on 2019-03-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0048_auto_20190315_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='access_level',
            field=models.PositiveIntegerField(choices=[(0, '仅比赛管理员可见'), (10, '仅受邀用户可见，赛后题目不公开'), (20, '仅受邀用户可见，赛后题目直接公开'), (30, '公开，需要比赛前注册'), (40, '公开')], default=0, verbose_name='访问控制'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='allowed_lang',
            field=models.CharField(default='c,cc14,cc17,cpp,java,pas,py2,pypy,pypy3,python,text', max_length=192, verbose_name='允许语言'),
        ),
    ]
