# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-28 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20170928_1327'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bloglikes',
            unique_together=set([('blog', 'user')]),
        ),
    ]
