# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-02 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170928_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='recommend',
            field=models.BooleanField(default=False),
        ),
    ]
