# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-25 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20171209_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='hide_revisions',
            field=models.BooleanField(default=False, verbose_name='Hide history versions'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Accessible to all users'),
        ),
        migrations.AddField(
            model_name='blog',
            name='revisions',
            field=models.ManyToManyField(to='blog.BlogRevision'),
        ),
    ]
