# Generated by Django 2.1.3 on 2018-11-06 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180225_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='edit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='hide_revisions',
            field=models.BooleanField(default=False, verbose_name='历史版本仅自己可见'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=128, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='所有用户可见'),
        ),
        migrations.AlterField(
            model_name='bloglikes',
            name='flag',
            field=models.CharField(choices=[('like', '点赞'), ('dislike', '点踩')], max_length=8),
        ),
        migrations.AlterField(
            model_name='blogrevision',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogrevision',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Blog'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.Problem'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
    ]
