# Generated by Django 2.1.3 on 2019-01-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181106_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create time'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='edit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update time'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='hide_revisions',
            field=models.BooleanField(default=False, verbose_name='History versions only available to you'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible to all users'),
        ),
    ]
