LANG_CHOICE = (
    ('c', 'C'),
    ('cpp', 'C++11'),
    ('python', 'Python 3'),
    ('java', 'Java 8'),

    ('c11', 'C11'),
    ('cpp98', 'C++'),
    ('cpp14', 'C++14'),
    ('csharp', 'C#'),
    ('python2', 'Python 2'),
    ('php', 'PHP 7'),
    ('fortran', 'Fortran'),
    ('perl', 'Perl'),
    ('ruby', 'Ruby'),
    ('objc', 'Objective-C'),
    ('haskell', 'Haskell'),
    ('scala', 'Scala'),
    ('lua', 'Lua'),
    ('lisp', 'Common Lisp'),
    ('js', 'Javascript'),
    ('go', 'Go'),
    ('ocaml', 'OCaml'),
    ('fsharp', 'F#'),
    ('pypy2', 'PyPy'),
    ('swift', 'Swift'),
    ('pascal', 'Pascal'),
    ('rust', 'Rust'),
    ('r', 'R'),
)