# Generated by Django 2.2.9 on 2020-02-04 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64, unique=True, verbose_name='指纹')),
                ('code', models.TextField(verbose_name='代码')),
                ('lang', models.CharField(choices=[('c', 'C'), ('cpp', 'C++11'), ('cc14', 'C++14'), ('cc17', 'C++17'), ('py2', 'Python 2'), ('python', 'Python 3'), ('pypy', 'PyPy'), ('pypy3', 'PyPy 3'), ('java', 'Java 8'), ('pas', 'Pascal'), ('text', 'Text')], default='cpp', max_length=12, verbose_name='语言')),
                ('public_access', models.PositiveIntegerField(choices=[(0, '只有自己可见'), (10, '对受邀用户可见'), (20, '对所有人可见')], default=20, verbose_name='访问权限')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('expire_after', models.IntegerField(choices=[(-1, '永不'), (1, '1 分钟'), (10, '10 分钟'), (60, '1 小时'), (300, '5 小时'), (1440, '1 天'), (43200, '30 天')], default=-1, verbose_name='过期')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pastes', to=settings.AUTH_USER_MODEL)),
                ('invited_users', models.ManyToManyField(related_name='invited_pastes', to=settings.AUTH_USER_MODEL, verbose_name='受邀用户')),
            ],
        ),
    ]
