# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 11:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('code', models.TextField()),
                ('lang', models.CharField(choices=[('c', 'C'), ('cpp', 'C++11'), ('python', 'Python 3'), ('java', 'Java 8'), ('cc14', 'C++14'), ('cc17', 'C++17'), ('cs', 'C#'), ('py2', 'Python 2'), ('scipy', 'Python (SCI)'), ('php', 'PHP 7'), ('perl', 'Perl'), ('hs', 'Haskell'), ('js', 'Javascript'), ('ocaml', 'OCaml'), ('pypy', 'PyPy'), ('pypy3', 'PyPy 3'), ('pas', 'Pascal'), ('rs', 'Rust'), ('scala', 'Scala'), ('text', 'Text')], default='cpp', max_length=12)),
                ('public_access', models.PositiveIntegerField(choices=[(0, 'Only to yourself'), (10, 'Only to invited'), (20, 'Open to everyone')], default=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('expire_after', models.IntegerField(choices=[(-1, 'Never'), (1, '1 minute'), (10, '10 minutes'), (60, '1 hour'), (300, '5 hours'), (1440, '1 day'), (43200, '30 days')], default=-1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_pastes', to=settings.AUTH_USER_MODEL)),
                ('invited_users', models.ManyToManyField(related_name='invited_pastes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
