# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 22:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pastes', to=settings.AUTH_USER_MODEL),
        ),
    ]
