# Generated by Django 2.1.3 on 2018-11-06 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0002_auto_20181010_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='code',
            field=models.TextField(verbose_name='代码'),
        ),
        migrations.AlterField(
            model_name='paste',
            name='expire_after',
            field=models.IntegerField(choices=[(-1, '永不'), (1, '1 分钟'), (10, '10 分钟'), (60, '1 小时'), (300, '5 小时'), (1440, '1 天'), (43200, '30 天')], default=-1, verbose_name='过期'),
        ),
        migrations.AlterField(
            model_name='paste',
            name='fingerprint',
            field=models.CharField(max_length=64, unique=True, verbose_name='指纹'),
        ),
        migrations.AlterField(
            model_name='paste',
            name='invited_users',
            field=models.ManyToManyField(related_name='invited_pastes', to=settings.AUTH_USER_MODEL, verbose_name='受邀用户'),
        ),
        migrations.AlterField(
            model_name='paste',
            name='lang',
            field=models.CharField(choices=[('c', 'C'), ('cpp', 'C++11'), ('python', 'Python 3'), ('java', 'Java 8'), ('cc14', 'C++14'), ('cc17', 'C++17'), ('cs', 'C#'), ('py2', 'Python 2'), ('scipy', 'Python (SCI)'), ('php', 'PHP 7'), ('perl', 'Perl'), ('hs', 'Haskell'), ('js', 'Javascript'), ('ocaml', 'OCaml'), ('pypy', 'PyPy'), ('pypy3', 'PyPy 3'), ('pas', 'Pascal'), ('rs', 'Rust'), ('scala', 'Scala'), ('text', 'Text')], default='cpp', max_length=12, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='paste',
            name='public_access',
            field=models.PositiveIntegerField(choices=[(0, '只有自己可见'), (10, '对受邀用户可见'), (20, '对所有人可见')], default=20, verbose_name='访问权限'),
        ),
    ]
