# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-19 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_remove_problem_created_by'),
        ('dispatcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serverproblemstatus',
            unique_together=set([('server', 'problem')]),
        ),
    ]
