# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0004_server_concurrency'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='runtime_multiplier',
            field=models.FloatField(default=1),
        ),
    ]
