# Generated by Django 2.1.3 on 2018-11-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0006_auto_20180715_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='server',
            name='concurrency',
            field=models.PositiveIntegerField(default=1, verbose_name='并发量'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.CharField(max_length=30, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.IntegerField(verbose_name='端口号'),
        ),
        migrations.AlterField(
            model_name='server',
            name='runtime_multiplier',
            field=models.FloatField(default=1, verbose_name='运行时间调整系数'),
        ),
        migrations.AlterField(
            model_name='server',
            name='token',
            field=models.CharField(max_length=192, verbose_name='密钥'),
        ),
    ]
