# Generated by Django 2.1.7 on 2019-03-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0008_server_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='master',
            field=models.BooleanField(default=True, verbose_name='主节点'),
        ),
    ]
