# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 21:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('input', models.TextField(blank=True, verbose_name='Input')),
                ('output', models.TextField(blank=True, verbose_name='Output')),
                ('sample', models.TextField(blank=True, verbose_name='Sample')),
                ('hint', models.TextField(blank=True, verbose_name='Hint')),
                ('source', models.CharField(blank=True, max_length=128, verbose_name='Source')),
                ('visible', models.BooleanField(default=False, verbose_name='Visible')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('time_limit', models.IntegerField(default=1000, verbose_name='Time limit per test')),
                ('sum_time_limit', models.IntegerField(default=10000, verbose_name='Time limit all tests')),
                ('memory_limit', models.IntegerField(default=256, verbose_name='Memory limit')),
                ('judge', models.CharField(blank=True, max_length=128, verbose_name='Judge indicator')),
                ('total_submit_number', models.IntegerField(default=0, verbose_name='Submit')),
                ('total_accept_number', models.IntegerField(default=0, verbose_name='Accept')),
                ('testdata_hash', models.CharField(blank=True, max_length=64, verbose_name='Testdata zip hash value')),
                ('testdata_size', models.IntegerField(default=1, verbose_name='Number of testdata cases')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
