# Generated by Django 2.2.17 on 2020-12-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='update_time',
            field=models.DateTimeField(),
        ),
    ]
