# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20170414_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-pk']},
        ),
    ]
