# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-29 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20170825_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(default=2000),
        ),
    ]
