# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-30 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_auto_20170920_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='alias',
            field=models.CharField(blank=True, max_length=64, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='cases',
            field=models.TextField(blank=True, verbose_name='Cases'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='checker',
            field=models.CharField(default='3813d49afd13857026fcd4643f51689c39639f83c2b4136b8d95ed285510a00f', max_length=64, verbose_name='Checker'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='hint',
            field=models.TextField(blank=True, verbose_name='Hint'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='input',
            field=models.TextField(blank=True, verbose_name='Input'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='interactor',
            field=models.CharField(blank=True, max_length=64, verbose_name='Interactor'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(default=256, verbose_name='Memory Limit'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output',
            field=models.TextField(blank=True, verbose_name='Output'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='points',
            field=models.TextField(blank=True, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='pretests',
            field=models.TextField(blank=True, verbose_name='Pretest'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample',
            field=models.TextField(blank=True, verbose_name='Sample'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='source',
            field=models.CharField(blank=True, max_length=128, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(default=2000, verbose_name='Time Limit'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(blank=True, max_length=192, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='validator',
            field=models.CharField(blank=True, max_length=64, verbose_name='Validator'),
        ),
    ]
