# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-01 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_auto_20170930_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='visible',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
