# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-01 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0013_taginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='group_config',
            field=models.TextField(blank=True, verbose_name='Group', default='~'),
        ),
    ]
