# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0018_auto_20180712_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemstatus',
            name='problem',
        ),
        migrations.DeleteModel(
            name='ProblemStatus',
        ),
    ]
