# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0019_auto_20180712_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='ac_list',
            field=models.TextField(),
        ),
    ]
