# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0021_auto_20180713_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='taginfo',
            name='parent_id',
            field=models.IntegerField(default=-1),
        ),
    ]
