# Generated by Django 2.1.3 on 2018-11-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0023_auto_20181108_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='reward',
            field=models.FloatField(default=9.9),
        ),
    ]
