# Generated by Django 2.1.7 on 2019-03-02 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0026_auto_20190115_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='judging_memory_limit',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='judging_time_limit',
        ),
    ]
