# Generated by Django 2.1.7 on 2019-03-06 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0027_auto_20190305_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='judging_memory_limit',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='judging_time_limit',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='package_id',
        ),
    ]
