# Generated by Django 2.2.3 on 2019-07-14 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0032_auto_20190317_0852'),
        ('django_comments_xtd', '0006_auto_20181204_0948'),
        ('problem', '0031_feedbackcompare'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_comments_xtd.XtdComment')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.Submission')),
            ],
        ),
    ]
