# Generated by Django 2.2.3 on 2019-11-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0032_commentsubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentSubmission',
        ),
    ]
