# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-25 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('key', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('val', models.TextField(blank=True)),
            ],
        ),
    ]
