# Generated by Django 2.2.9 on 2020-02-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('key', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('val', models.TextField(blank=True)),
            ],
        ),
    ]
