# Generated by Django 2.2.9 on 2020-02-04 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=192, verbose_name='标题')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('log_type', models.CharField(choices=[('fix', '问题修复'), ('add', '新功能'), ('del', '删除功能'), ('ref', '重构'), ('upd', '更新'), ('enhance', '加强')], max_length=10)),
                ('priority', models.PositiveIntegerField(choices=[(0, 'CRITICAL'), (1, 'HIGH'), (2, 'MEDIUM'), (3, 'LOW')])),
                ('is_about_polygon', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(-1, 'Pending'), (0, 'OK'), (1, 'Failed')], default=-1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.Email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'email')},
            },
        ),
        migrations.AddField(
            model_name='email',
            name='recipients',
            field=models.ManyToManyField(related_name='received_emails', through='backstage.EmailRecipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
