# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 10:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backstage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('log_type', models.CharField(choices=[('fix', 'BUG FIX'), ('add', 'NEW FEATURE'), ('del', 'REMOVE FEATURE'), ('ref', 'REFACTOR'), ('upd', 'UPDATE')], max_length=10)),
                ('priority', models.PositiveIntegerField(choices=[(0, 'CRITICAL'), (1, 'HIGH'), (2, 'MEDIUM'), (3, 'LOW')])),
                ('is_about_polygon', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('signature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='email',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
