# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0002_auto_20180712_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updatelog',
            old_name='signature',
            new_name='created_by',
        ),
    ]
