# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0003_auto_20180712_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatelog',
            name='log_type',
            field=models.CharField(choices=[('fix', 'BUG FIX'), ('add', 'NEW FEATURE'), ('del', 'REMOVE FEATURE'), ('ref', 'REFACTOR'), ('upd', 'UPDATE'), ('enhance', 'ENHANCEMENT')], max_length=10),
        ),
    ]
